"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var channelCreate_1 = require("./channelCreate");
Object.defineProperty(exports, "CHANNEL_CREATE", { enumerable: true, get: function () { return channelCreate_1.default; } });
var channelDelete_1 = require("./channelDelete");
Object.defineProperty(exports, "CHANNEL_DELETE", { enumerable: true, get: function () { return channelDelete_1.default; } });
var channelPinsUpdate_1 = require("./channelPinsUpdate");
Object.defineProperty(exports, "CHANNEL_PINS_UPDATE", { enumerable: true, get: function () { return channelPinsUpdate_1.default; } });
var channelUpdate_1 = require("./channelUpdate");
Object.defineProperty(exports, "CHANNEL_UPDATE", { enumerable: true, get: function () { return channelUpdate_1.default; } });
var guildBanAdd_1 = require("./guildBanAdd");
Object.defineProperty(exports, "GUILD_BAN_ADD", { enumerable: true, get: function () { return guildBanAdd_1.default; } });
var guildBanRemove_1 = require("./guildBanRemove");
Object.defineProperty(exports, "GUILD_BAN_REMOVE", { enumerable: true, get: function () { return guildBanRemove_1.default; } });
var guildCreate_1 = require("./guildCreate");
Object.defineProperty(exports, "GUILD_CREATE", { enumerable: true, get: function () { return guildCreate_1.default; } });
var guildDelete_1 = require("./guildDelete");
Object.defineProperty(exports, "GUILD_DELETE", { enumerable: true, get: function () { return guildDelete_1.default; } });
var guildEmojisUpdate_1 = require("./guildEmojisUpdate");
Object.defineProperty(exports, "GUILD_EMOJIS_UPDATE", { enumerable: true, get: function () { return guildEmojisUpdate_1.default; } });
var guildIntegrationsUpdate_1 = require("./guildIntegrationsUpdate");
Object.defineProperty(exports, "GUILD_INTEGRATIONS_UPDATE", { enumerable: true, get: function () { return guildIntegrationsUpdate_1.default; } });
var guildMemberAdd_1 = require("./guildMemberAdd");
Object.defineProperty(exports, "GUILD_MEMBER_ADD", { enumerable: true, get: function () { return guildMemberAdd_1.default; } });
var guildMemberRemove_1 = require("./guildMemberRemove");
Object.defineProperty(exports, "GUILD_MEMBER_REMOVE", { enumerable: true, get: function () { return guildMemberRemove_1.default; } });
var guildMembersChunk_1 = require("./guildMembersChunk");
Object.defineProperty(exports, "GUILD_MEMBERS_CHUNK", { enumerable: true, get: function () { return guildMembersChunk_1.default; } });
var guildMemberUpdate_1 = require("./guildMemberUpdate");
Object.defineProperty(exports, "GUILD_MEMBER_UPDATE", { enumerable: true, get: function () { return guildMemberUpdate_1.default; } });
var guildRoleCreate_1 = require("./guildRoleCreate");
Object.defineProperty(exports, "GUILD_ROLE_CREATE", { enumerable: true, get: function () { return guildRoleCreate_1.default; } });
var guildRoleDelete_1 = require("./guildRoleDelete");
Object.defineProperty(exports, "GUILD_ROLE_DELETE", { enumerable: true, get: function () { return guildRoleDelete_1.default; } });
var guildRoleUpdate_1 = require("./guildRoleUpdate");
Object.defineProperty(exports, "GUILD_ROLE_UPDATE", { enumerable: true, get: function () { return guildRoleUpdate_1.default; } });
var guildUpdate_1 = require("./guildUpdate");
Object.defineProperty(exports, "GUILD_UPDATE", { enumerable: true, get: function () { return guildUpdate_1.default; } });
var inviteCreate_1 = require("./inviteCreate");
Object.defineProperty(exports, "INVITE_CREATE", { enumerable: true, get: function () { return inviteCreate_1.default; } });
var inviteDelete_1 = require("./inviteDelete");
Object.defineProperty(exports, "INVITE_DELETE", { enumerable: true, get: function () { return inviteDelete_1.default; } });
var messageCreate_1 = require("./messageCreate");
Object.defineProperty(exports, "MESSAGE_CREATE", { enumerable: true, get: function () { return messageCreate_1.default; } });
var messageDelete_1 = require("./messageDelete");
Object.defineProperty(exports, "MESSAGE_DELETE", { enumerable: true, get: function () { return messageDelete_1.default; } });
var messageDeleteBulk_1 = require("./messageDeleteBulk");
Object.defineProperty(exports, "MESSAGE_DELETE_BULK", { enumerable: true, get: function () { return messageDeleteBulk_1.default; } });
var messageReactionAdd_1 = require("./messageReactionAdd");
Object.defineProperty(exports, "MESSAGE_REACTION_ADD", { enumerable: true, get: function () { return messageReactionAdd_1.default; } });
var messageReactionRemove_1 = require("./messageReactionRemove");
Object.defineProperty(exports, "MESSAGE_REACTION_REMOVE", { enumerable: true, get: function () { return messageReactionRemove_1.default; } });
var messageReactionRemoveAll_1 = require("./messageReactionRemoveAll");
Object.defineProperty(exports, "MESSAGE_REACTION_REMOVE_ALL", { enumerable: true, get: function () { return messageReactionRemoveAll_1.default; } });
var messageReactionRemoveEmoji_1 = require("./messageReactionRemoveEmoji");
Object.defineProperty(exports, "MESSAGE_REACTION_REMOVE_EMOJI", { enumerable: true, get: function () { return messageReactionRemoveEmoji_1.default; } });
var messageUpdate_1 = require("./messageUpdate");
Object.defineProperty(exports, "MESSAGE_UPDATE", { enumerable: true, get: function () { return messageUpdate_1.default; } });
var ready_1 = require("./ready");
Object.defineProperty(exports, "READY", { enumerable: true, get: function () { return ready_1.default; } });
var presenceUpdate_1 = require("./presenceUpdate");
Object.defineProperty(exports, "PRESENCE_UPDATE", { enumerable: true, get: function () { return presenceUpdate_1.default; } });
var typingStart_1 = require("./typingStart");
Object.defineProperty(exports, "TYPING_START", { enumerable: true, get: function () { return typingStart_1.default; } });
var userUpdate_1 = require("./userUpdate");
Object.defineProperty(exports, "USER_UPDATE", { enumerable: true, get: function () { return userUpdate_1.default; } });
var webhooksUpdate_1 = require("./webhooksUpdate");
Object.defineProperty(exports, "WEBHOOKS_UPDATE", { enumerable: true, get: function () { return webhooksUpdate_1.default; } });
var voiceServerUpdate_1 = require("./voiceServerUpdate");
Object.defineProperty(exports, "VOICE_SERVER_UPDATE", { enumerable: true, get: function () { return voiceServerUpdate_1.default; } });
var voiceStateUpdate_1 = require("./voiceStateUpdate");
Object.defineProperty(exports, "VOICE_STATE_UPDATE", { enumerable: true, get: function () { return voiceStateUpdate_1.default; } });
